import { useEffect, useState } from "react";
import { getExceptions } from "../services/api";
import PageHeader from "../components/common/PageHeader";

function Exceptions() {
    const [exceptions, setExceptions] = useState([]);
    const [loading, setLoading] = useState(true);

    useEffect(() => {
        loadExceptions();
    }, []);

    async function loadExceptions() {
        try {
            const response = await getExceptions();
            setExceptions(response.data.data || []);
        } catch (error) {
            console.error("Exceptions API error:", error);
        } finally {
            setLoading(false);
        }
    }

    if (loading) {
        return <p>Loading exceptions...</p>;
    }

    return (
        <div>
            <PageHeader
                title="Exception Center"
                subtitle="Live exceptions generated by the Phase 3 reconciliation engine"
            />

            <div className="bg-white rounded-xl shadow border border-slate-200 overflow-x-auto">
                <table className="w-full text-sm">
                    <thead className="bg-slate-100 text-slate-600">
                        <tr>
                            <th className="p-4 text-left">Txn ID</th>
                            <th className="p-4 text-left">Exception Code</th>
                            <th className="p-4 text-left">Left Source</th>
                            <th className="p-4 text-left">Right Source</th>
                            <th className="p-4 text-left">Business Date</th>
                            <th className="p-4 text-left">Remarks</th>
                        </tr>
                    </thead>

                    <tbody>
                        {exceptions.map((item) => (
                            <tr key={item.id} className="border-b hover:bg-slate-50">
                                <td className="p-4 font-semibold">
                                    {item.transaction_id}
                                </td>

                                <td className="p-4">
                                    <span className="px-3 py-1 rounded-full text-xs font-semibold bg-red-100 text-red-700">
                                        {item.exception_code}
                                    </span>
                                </td>

                                <td className="p-4">
                                    {item.left_source_id ?? "-"}
                                </td>

                                <td className="p-4">
                                    {item.right_source_id ?? "-"}
                                </td>

                                <td className="p-4">
                                    {item.business_date?.slice(0, 10)}
                                </td>

                                <td className="p-4">
                                    {item.remarks}
                                </td>
                            </tr>
                        ))}
                    </tbody>
                </table>

                {exceptions.length === 0 && (
                    <div className="p-8 text-center text-slate-500">
                        No exceptions found.
                    </div>
                )}
            </div>
        </div>
    );
}

export default Exceptions;